import { PrismaClient } from '@prisma/client'
import { createHash } from 'crypto'

const prisma = new PrismaClient()

function hash(s: string) {
  return createHash('md5').update(s).digest('hex')
}

const jobs = [
  {
    sourceId: 'b001',
    sourceName: 'boss.az',
    sourceUrl: 'https://boss.az/vacancies/1001',
    titleAz: 'Senior Backend Developer',
    titleEn: 'Senior Backend Developer',
    titleRu: 'Старший Backend Разработчик',
    company: 'Kapital Bank',
    location: 'Bakı',
    salary: '2000-3000 AZN',
    jobType: 'full-time',
    workMode: 'hybrid',
    experienceLevel: 'senior',
    categorySlug: 'it-tech',
    descriptionAz: 'Kapital Bank üçün yüksək yüklənmiş sistemlərin backend inkişafı. Node.js, PostgreSQL, Redis bilikləri tələb olunur.',
    descriptionEn: 'Backend development for high-load systems at Kapital Bank. Knowledge of Node.js, PostgreSQL, Redis required.',
    descriptionRu: 'Backend разработка высоконагруженных систем для Kapital Bank. Требуются знания Node.js, PostgreSQL, Redis.',
    requirementsAz: '5+ il təcrübə, Node.js, PostgreSQL, Redis, Docker, Kubernetes',
    requirementsEn: '5+ years experience, Node.js, PostgreSQL, Redis, Docker, Kubernetes',
    requirementsRu: '5+ лет опыта, Node.js, PostgreSQL, Redis, Docker, Kubernetes',
    publishDate: new Date('2026-03-20'),
    expiryDate: new Date('2026-04-20'),
  },
  {
    sourceId: 'b002',
    sourceName: 'boss.az',
    sourceUrl: 'https://boss.az/vacancies/1002',
    titleAz: 'Frontend Developer (React)',
    titleEn: 'Frontend Developer (React)',
    titleRu: 'Frontend Разработчик (React)',
    company: 'PASHA Holding',
    location: 'Bakı',
    salary: '1500-2500 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'mid',
    categorySlug: 'it-tech',
    descriptionAz: 'PASHA Holding üçün müasir React tətbiqlərinin inkişafı. TypeScript, Next.js bilikləri üstünlük verilir.',
    descriptionEn: 'Development of modern React applications for PASHA Holding. TypeScript, Next.js knowledge preferred.',
    descriptionRu: 'Разработка современных React приложений для PASHA Holding. Предпочтение TypeScript, Next.js.',
    requirementsAz: '3+ il React təcrübəsi, TypeScript, Redux, REST API',
    requirementsEn: '3+ years React experience, TypeScript, Redux, REST API',
    requirementsRu: '3+ лет опыта React, TypeScript, Redux, REST API',
    publishDate: new Date('2026-03-22'),
    expiryDate: new Date('2026-04-22'),
  },
  {
    sourceId: 'js001',
    sourceName: 'jobsearch.az',
    sourceUrl: 'https://jobsearch.az/vacancy/2001',
    titleAz: 'Satış Meneceri',
    titleEn: 'Sales Manager',
    titleRu: 'Менеджер по продажам',
    company: 'Azərenerji',
    location: 'Bakı',
    salary: '800-1200 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'mid',
    categorySlug: 'sales',
    descriptionAz: 'Korporativ müştərilərə satış, müqavilə bağlanması, satış planlarının yerinə yetirilməsi.',
    descriptionEn: 'Corporate client sales, contract signing, meeting sales targets.',
    descriptionRu: 'Продажи корпоративным клиентам, заключение договоров, выполнение планов продаж.',
    requirementsAz: '2+ il satış təcrübəsi, ünsiyyət bacarıqları, avtomobil',
    requirementsEn: '2+ years sales experience, communication skills, driving license',
    requirementsRu: '2+ года опыта в продажах, коммуникабельность, водительские права',
    publishDate: new Date('2026-03-18'),
    expiryDate: new Date('2026-04-18'),
  },
  {
    sourceId: 'hj001',
    sourceName: 'hellojob.az',
    sourceUrl: 'https://hellojob.az/vacancy/3001',
    titleAz: 'Maliyyə Analitiki',
    titleEn: 'Financial Analyst',
    titleRu: 'Финансовый Аналитик',
    company: 'ABB Bank',
    location: 'Bakı',
    salary: '1800-2500 AZN',
    jobType: 'full-time',
    workMode: 'hybrid',
    experienceLevel: 'mid',
    categorySlug: 'finance',
    descriptionAz: 'Maliyyə hesabatlarının hazırlanması, büdcə planlaması, investisiya təhlili.',
    descriptionEn: 'Preparation of financial reports, budget planning, investment analysis.',
    descriptionRu: 'Подготовка финансовых отчетов, бюджетное планирование, инвестиционный анализ.',
    requirementsAz: 'Ali maliyyə təhsili, Excel, 1C, CFA sertifikatı üstünlük',
    requirementsEn: 'Higher finance education, Excel, 1C, CFA certificate preferred',
    requirementsRu: 'Высшее финансовое образование, Excel, 1C, сертификат CFA приветствуется',
    publishDate: new Date('2026-03-25'),
    expiryDate: new Date('2026-04-25'),
  },
  {
    sourceId: 'sj001',
    sourceName: 'smartjob.az',
    sourceUrl: 'https://smartjob.az/vacancy/4001',
    titleAz: 'Mühəndis-Texnoloq',
    titleEn: 'Process Engineer',
    titleRu: 'Инженер-Технолог',
    company: 'SOCAR',
    location: 'Sumqayıt',
    salary: '2500-4000 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'senior',
    categorySlug: 'engineering',
    descriptionAz: 'Neft emalı zavodunda texnoloji proseslərin optimallaşdırılması, texniki sənədlərin hazırlanması.',
    descriptionEn: 'Optimization of technological processes at oil refinery, preparation of technical documentation.',
    descriptionRu: 'Оптимизация технологических процессов на НПЗ, подготовка технической документации.',
    requirementsAz: 'Kimya mühəndisliyi, 5+ il təcrübə, AutoCAD',
    requirementsEn: 'Chemical engineering degree, 5+ years experience, AutoCAD',
    requirementsRu: 'Химическая инженерия, 5+ лет опыта, AutoCAD',
    publishDate: new Date('2026-03-15'),
    expiryDate: new Date('2026-04-15'),
  },
  {
    sourceId: 'ej001',
    sourceName: 'ejob.az',
    sourceUrl: 'https://ejob.az/vacancy/5001',
    titleAz: 'HR Meneceri',
    titleEn: 'HR Manager',
    titleRu: 'HR Менеджер',
    company: 'Bakcell',
    location: 'Bakı',
    salary: '1200-1800 AZN',
    jobType: 'full-time',
    workMode: 'hybrid',
    experienceLevel: 'mid',
    categorySlug: 'hr',
    descriptionAz: 'İşçi seçimi, onboarding, performans qiymətləndirilməsi, korporativ mədəniyyətin inkişafı.',
    descriptionEn: 'Recruitment, onboarding, performance evaluation, corporate culture development.',
    descriptionRu: 'Подбор персонала, онбординг, оценка эффективности, развитие корпоративной культуры.',
    requirementsAz: '3+ il HR təcrübəsi, işçi qanunvericiliyi, psixologiya bilikləri',
    requirementsEn: '3+ years HR experience, labor law, psychology knowledge',
    requirementsRu: '3+ лет опыта в HR, трудовое законодательство, знание психологии',
    publishDate: new Date('2026-03-21'),
    expiryDate: new Date('2026-04-21'),
  },
  {
    sourceId: 'iq001',
    sourceName: 'iseqebul.az',
    sourceUrl: 'https://iseqebul.az/vacancy/6001',
    titleAz: 'Mühasib',
    titleEn: 'Accountant',
    titleRu: 'Бухгалтер',
    company: 'AzərGold',
    location: 'Gəncə',
    salary: '900-1400 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'mid',
    categorySlug: 'accounting',
    descriptionAz: 'Mühasibat uçotunun aparılması, vergi hesabatlarının hazırlanması, maliyyə sənədlərinin idarə edilməsi.',
    descriptionEn: 'Bookkeeping, tax report preparation, financial document management.',
    descriptionRu: 'Ведение бухгалтерского учета, подготовка налоговых отчетов, управление финансовыми документами.',
    requirementsAz: 'Mühasibat təhsili, 1C bilgisi, vergi qanunvericiliyi',
    requirementsEn: 'Accounting degree, 1C knowledge, tax legislation',
    requirementsRu: 'Бухгалтерское образование, знание 1С, налоговое законодательство',
    publishDate: new Date('2026-03-19'),
    expiryDate: new Date('2026-04-19'),
  },
  {
    sourceId: 'jo001',
    sourceName: 'jooble.az',
    sourceUrl: 'https://jooble.org/vacancy/7001',
    titleAz: 'UX/UI Dizayner',
    titleEn: 'UX/UI Designer',
    titleRu: 'UX/UI Дизайнер',
    company: 'Nar Mobile',
    location: 'Bakı',
    salary: '1300-2000 AZN',
    jobType: 'full-time',
    workMode: 'hybrid',
    experienceLevel: 'mid',
    categorySlug: 'design',
    descriptionAz: 'Mobil və veb tətbiqlər üçün istifadəçi interfeyslərinin dizaynı, prototiplərin hazırlanması.',
    descriptionEn: 'Design of user interfaces for mobile and web applications, prototype creation.',
    descriptionRu: 'Дизайн пользовательских интерфейсов для мобильных и веб-приложений, создание прототипов.',
    requirementsAz: 'Figma, Adobe XD, portfolio, 2+ il təcrübə',
    requirementsEn: 'Figma, Adobe XD, portfolio, 2+ years experience',
    requirementsRu: 'Figma, Adobe XD, портфолио, 2+ года опыта',
    publishDate: new Date('2026-03-24'),
    expiryDate: new Date('2026-04-24'),
  },
  {
    sourceId: 'hr001',
    sourceName: 'hrin.az',
    sourceUrl: 'https://hrin.az/vacancy/8001',
    titleAz: 'Logistika Koordinatoru',
    titleEn: 'Logistics Coordinator',
    titleRu: 'Координатор по Логистике',
    company: 'Azerbaijan Airlines',
    location: 'Bakı',
    salary: '1100-1600 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'mid',
    categorySlug: 'logistics',
    descriptionAz: 'Yük daşımalarının təşkili, gömrük rəsmiləşdirilməsi, anbar idarəçiliyi.',
    descriptionEn: 'Freight transport organization, customs clearance, warehouse management.',
    descriptionRu: 'Организация грузоперевозок, таможенное оформление, управление складом.',
    requirementsAz: '2+ il logistika təcrübəsi, gömrük bilikləri, ingiliscə',
    requirementsEn: '2+ years logistics experience, customs knowledge, English',
    requirementsRu: '2+ лет опыта в логистике, знание таможни, английский язык',
    publishDate: new Date('2026-03-23'),
    expiryDate: new Date('2026-04-23'),
  },
  {
    sourceId: 'b003',
    sourceName: 'boss.az',
    sourceUrl: 'https://boss.az/vacancies/1003',
    titleAz: 'Marketing Meneceri',
    titleEn: 'Marketing Manager',
    titleRu: 'Менеджер по Маркетингу',
    company: 'Silk Way Airlines',
    location: 'Bakı',
    salary: '1500-2200 AZN',
    jobType: 'full-time',
    workMode: 'hybrid',
    experienceLevel: 'mid',
    categorySlug: 'marketing',
    descriptionAz: 'Rəqəmsal marketinq strategiyalarının hazırlanması, sosial media idarəçiliyi, SEO/SEM.',
    descriptionEn: 'Digital marketing strategy development, social media management, SEO/SEM.',
    descriptionRu: 'Разработка стратегий цифрового маркетинга, управление соцсетями, SEO/SEM.',
    requirementsAz: 'Rəqəmsal marketinq bilikləri, Google Ads, Facebook Ads, analitika',
    requirementsEn: 'Digital marketing knowledge, Google Ads, Facebook Ads, analytics',
    requirementsRu: 'Знание цифрового маркетинга, Google Ads, Facebook Ads, аналитика',
    publishDate: new Date('2026-03-26'),
    expiryDate: new Date('2026-04-26'),
  },
  {
    sourceId: 'sj002',
    sourceName: 'smartjob.az',
    sourceUrl: 'https://smartjob.az/vacancy/4002',
    titleAz: 'Tikinti Layihə Meneceri',
    titleEn: 'Construction Project Manager',
    titleRu: 'Менеджер Строительного Проекта',
    company: 'Embawood',
    location: 'Bakı',
    salary: '2000-3500 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'senior',
    categorySlug: 'construction',
    descriptionAz: 'Tikinti layihələrinin idarə edilməsi, subpodratçılarla işin koordinasiyası, büdcə nəzarəti.',
    descriptionEn: 'Construction project management, subcontractor coordination, budget control.',
    descriptionRu: 'Управление строительными проектами, координация субподрядчиков, контроль бюджета.',
    requirementsAz: 'İnşaat mühəndisliyi, PMP sertifikatı, MS Project, 7+ il təcrübə',
    requirementsEn: 'Civil engineering, PMP certificate, MS Project, 7+ years experience',
    requirementsRu: 'Строительная инженерия, сертификат PMP, MS Project, 7+ лет опыта',
    publishDate: new Date('2026-03-17'),
    expiryDate: new Date('2026-04-17'),
  },
  {
    sourceId: 'hj002',
    sourceName: 'hellojob.az',
    sourceUrl: 'https://hellojob.az/vacancy/3002',
    titleAz: 'Müştəri Xidməti Operatoru',
    titleEn: 'Customer Support Operator',
    titleRu: 'Оператор Службы Поддержки',
    company: 'Azercell',
    location: 'Bakı',
    salary: '600-900 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'junior',
    categorySlug: 'customer-support',
    descriptionAz: 'Müştəri sorğularına cavab vermək, texniki dəstək, müştəri məmnuniyyətinin təmin edilməsi.',
    descriptionEn: 'Responding to customer inquiries, technical support, ensuring customer satisfaction.',
    descriptionRu: 'Ответы на запросы клиентов, техническая поддержка, обеспечение удовлетворенности клиентов.',
    requirementsAz: 'Yaxşı ünsiyyət bacarıqları, kompüter savadlılığı, azərbaycan/rus dili',
    requirementsEn: 'Good communication skills, computer literacy, Azerbaijani/Russian language',
    requirementsRu: 'Хорошие коммуникативные навыки, компьютерная грамотность, азербайджанский/русский язык',
    publishDate: new Date('2026-03-28'),
    expiryDate: new Date('2026-04-28'),
  },
  {
    sourceId: 'js002',
    sourceName: 'jobsearch.az',
    sourceUrl: 'https://jobsearch.az/vacancy/2002',
    titleAz: 'Hüquqşünas',
    titleEn: 'Lawyer',
    titleRu: 'Юрист',
    company: 'Rabitəbank',
    location: 'Bakı',
    salary: '1400-2000 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'mid',
    categorySlug: 'legal',
    descriptionAz: 'Müqavilələrin hazırlanması və yoxlanması, hüquqi məsləhətlər, məhkəmə proseslərinin idarə edilməsi.',
    descriptionEn: 'Contract drafting and review, legal consultations, court process management.',
    descriptionRu: 'Составление и проверка договоров, юридические консультации, управление судебными процессами.',
    requirementsAz: 'Hüquq təhsili, mülki hüquq, müqavilə hüququ, ingiliscə',
    requirementsEn: 'Law degree, civil law, contract law, English language',
    requirementsRu: 'Юридическое образование, гражданское право, договорное право, английский язык',
    publishDate: new Date('2026-03-16'),
    expiryDate: new Date('2026-04-16'),
  },
  {
    sourceId: 'ej002',
    sourceName: 'ejob.az',
    sourceUrl: 'https://ejob.az/vacancy/5002',
    titleAz: 'Müəllim (Riyaziyyat)',
    titleEn: 'Teacher (Mathematics)',
    titleRu: 'Учитель (Математика)',
    company: 'Xəzər Universiteti',
    location: 'Bakı',
    salary: '700-1100 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'mid',
    categorySlug: 'education',
    descriptionAz: 'Ali məktəb tələbələrinə riyaziyyat dərslərinin tədris edilməsi, imtahan suallarının hazırlanması.',
    descriptionEn: 'Teaching mathematics to university students, exam question preparation.',
    descriptionRu: 'Преподавание математики студентам университета, подготовка экзаменационных вопросов.',
    requirementsAz: 'Riyaziyyat magistraturası, tədris təcrübəsi, akademik yazı',
    requirementsEn: 'Mathematics masters degree, teaching experience, academic writing',
    requirementsRu: 'Магистратура по математике, опыт преподавания, академическое письмо',
    publishDate: new Date('2026-03-14'),
    expiryDate: new Date('2026-04-14'),
  },
  {
    sourceId: 'hr002',
    sourceName: 'hrin.az',
    sourceUrl: 'https://hrin.az/vacancy/8002',
    titleAz: 'Neft-Qaz Mühəndisi',
    titleEn: 'Oil & Gas Engineer',
    titleRu: 'Нефтегазовый Инженер',
    company: 'BP Azerbaijan',
    location: 'Bakı',
    salary: '4000-6000 AZN',
    jobType: 'full-time',
    workMode: 'office',
    experienceLevel: 'senior',
    categorySlug: 'oil-gas',
    descriptionAz: 'Neft hasilatının optimallaşdırılması, quyu monitorinqi, reservoir modelləşdirilməsi.',
    descriptionEn: 'Oil production optimization, well monitoring, reservoir modeling.',
    descriptionRu: 'Оптимизация добычи нефти, мониторинг скважин, моделирование пласта.',
    requirementsAz: 'Neft-qaz mühəndisliyi, 8+ il təcrübə, ECLIPSE, Petrel',
    requirementsEn: 'Petroleum engineering, 8+ years experience, ECLIPSE, Petrel',
    requirementsRu: 'Нефтегазовая инженерия, 8+ лет опыта, ECLIPSE, Petrel',
    publishDate: new Date('2026-03-27'),
    expiryDate: new Date('2026-04-27'),
  },
]

async function main() {
  console.log('Seeding database...')

  // Clear existing data
  await prisma.job.deleteMany()
  await prisma.source.deleteMany()
  await prisma.importLog.deleteMany()

  // Seed sources
  const sources = [
    { name: 'boss.az', url: 'https://boss.az' },
    { name: 'jobsearch.az', url: 'https://jobsearch.az' },
    { name: 'hellojob.az', url: 'https://hellojob.az' },
    { name: 'smartjob.az', url: 'https://smartjob.az' },
    { name: 'ejob.az', url: 'https://ejob.az' },
    { name: 'iseqebul.az', url: 'https://iseqebul.az' },
    { name: 'jooble.az', url: 'https://jooble.org/az' },
    { name: 'hrin.az', url: 'https://hrin.az' },
  ]

  for (const source of sources) {
    await prisma.source.upsert({
      where: { name: source.name },
      update: {},
      create: source,
    })
  }

  // Seed jobs
  for (const job of jobs) {
    const contentHash = hash(`${job.titleAz}${job.company}${job.sourceUrl}`)
    await prisma.job.create({
      data: {
        ...job,
        contentHash,
      },
    })
  }

  console.log(`✅ Seeded ${jobs.length} jobs and ${sources.length} sources`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
